### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by MarcusElg** [oitsjustjose/Geolosys#107]
## Versions:

- Minecraft Forge: 1.12.2-14.23.3.2680 (latest)
- Geolosys: 1.9 (latest)

## What happens:
It crashes on start

## What should happen:
Not crash 😄 

## Logs (if necessary):
---- Minecraft Crash Report ----
// Ouch. That hurt :(

Time: 5/9/18 5:32 PM
Description: Initializing game

java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(String.java:1954)
	at com.oitsjustjose.geolosys.util.HelperFunctions.getTranslation(HelperFunctions.java:35)
	at com.oitsjustjose.geolosys.util.DepthFinder.registerEvent(DepthFinder.java:73)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_29_DepthFinder_registerEvent_ItemTooltipEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.event.ForgeEventFactory.onItemTooltip(ForgeEventFactory.java:324)
	at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:889)
	at net.minecraft.client.Minecraft.lambda$populateSearchTreeManager$1(Minecraft.java:575)
	at net.minecraft.client.Minecraft$$Lambda$114/244477902.apply(Unknown Source)
	at net.minecraft.client.util.SearchTree.func_194042_b(SourceFile:49)
	at net.minecraft.client.util.SearchTree.func_194043_a(SourceFile:44)
	at net.minecraft.client.Minecraft$$Lambda$116/1781410358.accept(Unknown Source)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at net.minecraft.client.Minecraft.func_193986_ar(Minecraft.java:589)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:528)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at java.lang.String.substring(String.java:1954)
	at com.oitsjustjose.geolosys.util.HelperFunctions.getTranslation(HelperFunctions.java:35)
	at com.oitsjustjose.geolosys.util.DepthFinder.registerEvent(DepthFinder.java:73)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_29_DepthFinder_registerEvent_ItemTooltipEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.event.ForgeEventFactory.onItemTooltip(ForgeEventFactory.java:324)
	at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:889)
	at net.minecraft.client.Minecraft.lambda$populateSearchTreeManager$1(Minecraft.java:575)
	at net.minecraft.client.Minecraft$$Lambda$114/244477902.apply(Unknown Source)
	at net.minecraft.client.util.SearchTree.func_194042_b(SourceFile:49)
	at net.minecraft.client.util.SearchTree.func_194043_a(SourceFile:44)
	at net.minecraft.client.Minecraft$$Lambda$116/1781410358.accept(Unknown Source)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at net.minecraft.client.Minecraft.func_193986_ar(Minecraft.java:589)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:528)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 106519224 bytes (101 MB) / 402653184 bytes (384 MB) up to 1073741824 bytes (1024 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.3.2680 6 mods loaded, 6 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID           | Version      | Source                        | Signature                                |
	|:----- |:------------ |:------------ |:----------------------------- |:---------------------------------------- |
	| UCH   | minecraft    | 1.12.2       | minecraft.jar                 | None                                     |
	| UCH   | mcp          | 9.42         | minecraft.jar                 | None                                     |
	| UCH   | FML          | 8.0.99.99    | forge-1.12.2-14.23.3.2680.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | forge        | 14.23.3.2680 | forge-1.12.2-14.23.3.2680.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | dynamictrees | 1.12.2-0.7.6 | DynamicTrees-1.12.2-0.7.6.jar | None                                     |
	| UCH   | geolosys     | 1.9          | Geolosys-1.12.2-1.9.jar       | None                                     |

	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'Intel' Version: '4.3.0 - Build 20.19.15.4642' Renderer: 'Intel(R) HD Graphics 4400'
	Launched Version: 1.12.2-forge1.12.2-14.23.3.2680
	LWJGL: 2.9.4
	OpenGL: Intel(R) HD Graphics 4400 GL version 4.3.0 - Build 20.19.15.4642, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz

**Comment by oitsjustjose** [comment]
What language are you using? It may be a case of needing a try-catch for unsupported languages.

**Comment by MarcusElg** [comment]
brittish english

**Comment by MarcusElg** [comment]
en_gb

**Comment by oitsjustjose** [comment]
That’s why. Good catch. When I get a chance (I’m at work currently) I’ll push a fix.

**Comment by MarcusElg** [comment]
thx, would really like to try out your mod!

**Comment by oitsjustjose** [comment]
If it’s a rush, you can change your language to en_US.
