### ISSUE TITLE
Disabling WorldGen Causes Crash

### ISSUE THREAD

**Issue by Graagh** [oitsjustjose/Geolosys#13]
If B:"Replace Stone Variant Deposits" is set to false in the config, the stonegenArray will be empty. It causes this crash:

Description: Exception in server tick loop

java.lang.IllegalArgumentException: bound must be positive
	at java.util.Random.nextInt(Random.java:388)
	at com.oitsjustjose.geolosys.world.StoneGenerator.generate(StoneGenerator.java:67)
	at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:167)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1015)
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:995)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:157)
	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:343)
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:173)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:196)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:483)
	at java.lang.Thread.run(Thread.java:745)

Pretty sure the same thing will happen in OreGenerator.java as well if, for some reason, one were to disable all ore gen.

**Comment by oitsjustjose** [comment]
I'll look into it and have it fixed by 1.5 :)
