### ISSUE TITLE
Crash Upon Entering End Dimension 1.18

### ISSUE THREAD

**Issue by elder-sign** [oitsjustjose/Geolosys#289]
## Versions:

- Minecraft Forge: 39.0.8
- Geolosys: 7.0.1 Beta 1
- JourneyMap (optional): journeymap-1.18.1-5.8.0beta4
- ImmersiveEngineering (optional): ImmersiveEngineering-1.18.1-7.0.1-144

## What happens:
 MC crashes upon trying to enter the End dimension. Crash log indicates Geolosys failing to generate pluton as reason.
## What should happen:
Should not crash.
## Logs (if necessary):

Time: 12/27/21, 2:41 AM
Description: Feature placement

java.lang.NullPointerException: Cannot invoke "com.oitsjustjose.geolosys.api.world.IDeposit.generate(net.minecraft.world.level.WorldGenLevel, net.minecraft.core.BlockPos, com.oitsjustjose.geolosys.common.world.capability.IDepositCapability)" because "pluton" is null
	at com.oitsjustjose.geolosys.common.world.feature.DepositFeature.m_142674_(DepositFeature.java:56) ~[Geolosys-1.18.1-7.0.1-beta-1.jar%23102!:7.0.1-beta-1] {re:classloading}
	at net.minecraft.world.level.levelgen.feature.ConfiguredFeature.m_65385_(ConfiguredFeature.java:80) ~[client-1.18.1-20211210.034407-srg.jar%23169!:?] {re:classloading}
	at net.minecraft.world.level.levelgen.placement.PlacedFeature.m_191789_(PlacedFeature.java:56) ~[client-1.18.1-20211210.034407-srg.jar%23169!:?] {re:classloading,pl:accesstransformer:B}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?] {}
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411) ~[?:?] {}
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?] {}
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276) ~[?:?] {}
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411) ~[?:?] {}
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?] {}
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?] {}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?] {}
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?] {}
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?] {}
	at net.minecraft.world.level.levelgen.placement.PlacedFeature.m_191797_(PlacedFeature.java:55) ~[client-1.18.1-20211210.034407-srg.jar%23169!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.level.levelgen.placement.PlacedFeature.m_191806_(PlacedFeature.java:44) ~[client-1.18.1-20211210.034407-srg.jar%23169!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.level.chunk.ChunkGenerator.m_183372_(ChunkGenerator.java:316) ~[client-1.18.1-20211210.034407-srg.jar%23169!:?] {re:mixin,re:classloading,pl:mixin:APP:citadel.mixins.json:ChunkGeneratorMixin,pl:mixin:APP:repurposed_structures.mixins.json:world.ChunkGeneratorAccessor,pl:mixin:APP:supplementaries.mixins.json:accessors.ChunkGeneratorAccessor,pl:mixin:A}
	at net.minecraft.world.level.chunk.ChunkStatus.m_187807_(ChunkStatus.java:135) ~[client-1.18.1-20211210.034407-srg.jar%23169!:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.world.level.chunk.ChunkStatus.m_187788_(ChunkStatus.java:262) ~[client-1.18.1-20211210.034407-srg.jar%23169!:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.level.ChunkMap.lambda$scheduleChunkGeneration$20(ChunkMap.java:552) ~[client-1.18.1-20211210.034407-srg.jar%23169!:?] {re:classloading,pl:accesstransformer:B}
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-4.0.26.jar%2324!:?] {}
	at net.minecraft.server.level.ChunkMap.lambda$scheduleChunkGeneration$22(ChunkMap.java:550) ~[client-1.18.1-20211210.034407-srg.jar%23169!:?] {re:classloading,pl:accesstransformer:B}
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?] {}
	at net.minecraft.server.level.ChunkTaskPriorityQueueSorter.m_143188_(ChunkTaskPriorityQueueSorter.java:58) ~[client-1.18.1-20211210.034407-srg.jar%23169!:?] {re:classloading}
	at net.minecraft.util.thread.ProcessorMailbox.m_18759_(ProcessorMailbox.java:91) ~[client-1.18.1-20211210.034407-srg.jar%23169!:?] {re:classloading}
	at net.minecraft.util.thread.ProcessorMailbox.m_18747_(ProcessorMailbox.java:146) ~[client-1.18.1-20211210.034407-srg.jar%23169!:?] {re:classloading}
	at net.minecraft.util.thread.ProcessorMailbox.run(ProcessorMailbox.java:102) ~[client-1.18.1-20211210.034407-srg.jar%23169!:?] {re:classloading}
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

## Additional Comments:

Deleting dimension folder for the end did not fix the issue, nether generates as intended.

[crash-2021-12-27_02.41.49-server.txt](https://github.com/oitsjustjose/Geolosys/files/7781437/crash-2021-12-27_02.41.49-server.txt)

**Comment by oitsjustjose** [comment]
Thanks for letting me know - new build will be out shortly.

**Comment by elder-sign** [comment]
Thank you , I appreciate the quick response c:
