### ISSUE TITLE
Error on worldgen

### ISSUE THREAD

**Issue by RiverC** [oitsjustjose/Geolosys#49]
```
Time: 1/1/18 7:26 PM
Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
	at com.oitsjustjose.geolosys.world.OreGenerator$OreGen.generate(OreGenerator.java:69)
	at com.oitsjustjose.geolosys.world.OreGenerator.generate(OreGenerator.java:40)
	at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:167)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1016)
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:982)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:157)
	at net.minecraft.world.World.func_72964_e(World.java:309)
	at net.minecraft.world.World.func_175726_f(World.java:304)
	at net.minecraft.world.World.func_180495_p(World.java:910)
	at net.minecraft.world.World.func_190529_b(World.java:580)
	at net.minecraft.world.World.func_190522_c(World.java:482)
	at net.minecraft.world.World.markAndNotifyBlock(World.java:389)
	at net.minecraft.world.World.func_180501_a(World.java:360)
	at net.minecraft.world.gen.feature.WorldGenMinable.func_180709_b(WorldGenMinable.java:79)
	at nmd.primal.core.common.world.WorldGenCommon.generate(WorldGenCommon.java:193)
	at nmd.primal.core.common.world.generators.PrimalWorld.generate(PrimalWorld.java:41)
	at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:167)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1016)
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:996)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:157)
	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:344)
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:173)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:196)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484)
	at java.lang.Thread.run(Thread.java:745)
```

Not wholly sure the cause here. But updating version and copying over the new configs generated seems to cause generation of a new world to hang, and the cause is that the server has crashed.

EDIT: deleting my modified configs (both the json and the cfg) prevents the error. I'll try to figure out which option messed things up.

**Comment by oitsjustjose** [comment]
I see what's happened..

If the `geolosys_ores.json` file is missing an ore entry, Geolosys itself never tries to re-initialize them (I should, I know, and I shall). So it could be that if you had an old version of the `geolosys_ores.json` file and I added a new ore - like Beryl - then it would be referencing `berylDimBlacklist`, which wouldn't have been read in from the JSON and would therefore be null.

**Comment by RiverC** [comment]
Yeah, I re-added my changes, re-testing the world gen a couple at a time and it worked. It certainly looks like the json got invalidated, and the main problem with having a single json file for config, as I've learned from my own projects, is that if one entry is messed up, the json-reader often returns null for the whole object. XML of course has the same issue.
