### ISSUE TITLE
[Console] Generating Error from Galacticraft

### ISSUE THREAD

**Issue by artdude543** [oitsjustjose/Geolosys#91]
Working on testing server stability with SevTech 3.0.4 and noticed while generating a metric tonne of chunks this error being spat out in the console. Did not notice this on the pervious version but I know Dark changed the configs a bit with the mod configs. If you need more info just asked but Galaticcraft is blaming you for this.

Mod Version: 1.8.10b

```
> [23:56:21] [Server thread/ERROR] [Galacticraft]: Error in another mod's worldgen. This is *NOT* a Galacticraft bug, report it to the other mod please.
> [23:56:21] [Server thread/ERROR] [Galacticraft]: Details:- Dimension:7 Chunk cx,cz:3,3 Seed:-928907734
> [23:56:21] [Server thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.TransformerHooks:otherModGenerate:189]: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
> [23:56:21] [Server thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.TransformerHooks:otherModGenerate:189]: at java.lang.String.substring(String.java:1967)
> [23:56:21] [Server thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.TransformerHooks:otherModGenerate:189]: at com.oitsjustjose.geolosys.world.OreGenerator$OreGen.generate(OreGenerator.java:90)
> [23:56:21] [Server thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.TransformerHooks:otherModGenerate:189]: at com.oitsjustjose.geolosys.world.OreGenerator.generate(OreGenerator.java:45)
> [23:56:21] [Server thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.TransformerHooks:otherModGenerate:189]: at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:167)
> [23:56:21] [Server thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.TransformerHooks:otherModGenerate:189]: at micdoodle8.mods.galacticraft.core.TransformerHooks.otherModGenerate(TransformerHooks.java:184)
> [23:56:21] [Server thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.TransformerHooks:otherModGenerate:189]: at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1016)
> [23:56:21] [Server thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.TransformerHooks:otherModGenerate:189]: at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:982)
> [23:56:21] [Server thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.TransformerHooks:otherModGenerate:189]: at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:157)
> [23:56:21] [Server thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.TransformerHooks:otherModGenerate:189]: at net.minecraft.world.World.func_72964_e(World.java:309)
> [23:56:21] [Server thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.TransformerHooks:otherModGenerate:189]: at net.minecraftforge.server.command.ChunkGenWorker.work(ChunkGenWorker.java:144)
> [23:56:21] [Server thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.TransformerHooks:otherModGenerate:189]: at net.minecraftforge.common.WorldWorkerManager.tick(WorldWorkerManager.java:48)
> [23:56:21] [Server thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.TransformerHooks:otherModGenerate:189]: at net.minecraftforge.common.ForgeInternalHandler.onServerTick(ForgeInternalHandler.java:90)
> [23:56:21] [Server thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.TransformerHooks:otherModGenerate:189]: at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_550_ForgeInternalHandler_onServerTick_ServerTickEvent.invoke(.dynamic)
> [23:56:21] [Server thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.TransformerHooks:otherModGenerate:189]: at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
> [23:56:21] [Server thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.TransformerHooks:otherModGenerate:189]: at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
> [23:56:21] [Server thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.TransformerHooks:otherModGenerate:189]: at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:265)
> [23:56:21] [Server thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.TransformerHooks:otherModGenerate:189]: at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:710)
> [23:56:21] [Server thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.TransformerHooks:otherModGenerate:189]: at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
> [23:56:21] [Server thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.TransformerHooks:otherModGenerate:189]: at java.lang.Thread.run(Thread.java:748)
```

**Comment by oitsjustjose** [comment]
It *is* technically my fault, but in the sense that I assumed people wouldn't be dumb about the way they register their blocks. I know the problem and how to fix it *partly*, but not completely.

**Comment by artdude543** [comment]
Okies  just wanted to point it out and have a log somewhere before we got issues flooding in for the pack :)

**Comment by oitsjustjose** [comment]
[This](https://github.com/oitsjustjose/Geolosys/commit/b66f4d9a741571245c2cd9ccaab2d9c280f1f01d#diff-eeb8694af02b61487fe9c3f4af48b26f) should fix it :)

I broke other stuff too, expect a SevTech 3.0.5 soon™️
